### ISSUE TITLE
Coredump 

### ISSUE THREAD

**Issue by freswa** [nullobsi/pass-secrets#12]
When using fractal-git with pass-secrets on Arch, it coredumps quite reproducibly.

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f557a49f2d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f557a44fa08 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f557a438538 in __GI_abort () at abort.c:79
#4  0x00007f557a69ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007f557a6b011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007f557a6b0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007f557a6b03ed in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x55de57d817d0, dest=0x55de57d4eb00) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x000055de57d41007 in ?? ()
#9  0x000055de57d4d7b2 in ?? ()
#10 0x000055de57d4ee9a in ?? ()
#11 0x00007f557aa693a6 in sdbus::internal::Object::sdbus_method_callback(sd_bus_message*, void*, sd_bus_error*) () from /usr/lib/libsdbus-c++.so.1
#12 0x00007f557a96fe2d in method_callbacks_run (found_object=0x7ffea0918848, require_fallback=false, c=0x55de59d71d40, m=0x55de59d80ce0, bus=0x55de59d6e410) at ../systemd-stable/src/libsystemd/sd-bus/bus-objects.c:406
#13 object_find_and_run (bus=0x55de59d6e410, m=0x55de59d80ce0, p=0x55de59d80948 "/org/freedesktop/secrets", require_fallback=false, found_object=0x7ffea0918848) at ../systemd-stable/src/libsystemd/sd-bus/bus-objects.c:1319
#14 0x00007f557a9862be in bus_process_object (m=<optimized out>, bus=<optimized out>) at ../systemd-stable/src/libsystemd/sd-bus/bus-objects.c:1439
#15 process_message (m=0x55de59d80ce0, bus=0x55de59d6e410) at ../systemd-stable/src/libsystemd/sd-bus/sd-bus.c:2976
#16 process_running (ret=0x0, bus=0x55de59d6e410) at ../systemd-stable/src/libsystemd/sd-bus/sd-bus.c:3018
#17 bus_process_internal (bus=<optimized out>, ret=0x0) at ../systemd-stable/src/libsystemd/sd-bus/sd-bus.c:3238
#18 0x00007f557aa5f876 in sdbus::internal::Connection::processPendingRequest() () from /usr/lib/libsdbus-c++.so.1
#19 0x000055de57d42487 in ?? ()
#20 0x00007f557a439850 in __libc_start_call_main (main=main@entry=0x55de57d41280, argc=argc@entry=1, argv=argv@entry=0x7ffea0918cb8) at ../sysdeps/nptl/libc_start_call_main.h:58
#21 0x00007f557a43990a in __libc_start_main_impl (main=0x55de57d41280, argc=1, argv=0x7ffea0918cb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffea0918ca8) at ../csu/libc-start.c:360
#22 0x000055de57d42fd5 in ?? ()

**Comment by ThatChemical5117** [comment]
I also have a similar issue when trying re-login in to Minecraft launcher. the program core dumps. I included the resulting core file as a tar archive. 
[core.tar.gz](https://github.com/user-attachments/files/16184216/core.tar.gz)
